services:
  database:
    image: postgres
    ports: 
      - 5434:5432
    expose:
      - 5434
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pomodoro